WebJokesApp/Models/ErrorViewModel.cs
namespace WebJokesApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebJokesApp/Models/Jokes.cs
namespace WebJokesApp.Models
{
    public class Jokes
    {

        public int Id { get; set; }

        public string JokePergunta { get; set; }
        public string JokeResposta { get; set; }

        public string IdUser { get; set; }

        public Jokes()
        {
            Id = 0;
            JokePergunta = string.Empty;
            JokeResposta = string.Empty;
            IdUser = string.Empty;
        }
    }
}

WebJokesApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebJokesApp.Models;

namespace WebJokesApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebJokesApp/Controllers/JokesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebJokesApp.Data;
using WebJokesApp.Models;

namespace WebJokesApp.Controllers
{
    public class JokesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JokesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Jokes
        public async Task<IActionResult> Index()
        {
              return _context.Jokes != null ? 
                          View(await _context.Jokes.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Jokes'  is null.");
        }

        // GET: ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // POST : S

        public async Task<IActionResult> ShowFormResults(string SearchPhrase)
        {
            return _context.Jokes != null ?
            View("Index",await _context.Jokes.Where( j => j.JokePergunta.Contains(SearchPhrase) ).ToListAsync()) :
            Problem("Entity set 'ApplicationDbContext.Jokes'  is null.");
        }

        // GET: Jokes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Jokes == null)
            {
                return NotFound();
            }

            var jokes = await _context.Jokes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jokes == null)
            {
                return NotFound();
            }

            return View(jokes);
        }

        // GET: Jokes/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jokes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JokePergunta,JokeResposta, IdUser")] Jokes jokes)
        {
            if (ModelState.IsValid)
            {
                jokes.IdUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
                _context.Add(jokes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jokes);
        }

        // GET: Jokes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Jokes == null)
            {
                return NotFound();
            }

            var jokes = await _context.Jokes.FindAsync(id);
            if (jokes == null)
            {
                return NotFound();
            }
            return View(jokes);
        }

        // POST: Jokes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JokePergunta,JokeResposta")] Jokes jokes)
        {
            if (id != jokes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jokes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JokesExists(jokes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jokes);
        }

        // GET: Jokes/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Jokes == null)
            {
                return NotFound();
            }

            var jokes = await _context.Jokes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jokes == null)
            {
                return NotFound();
            }

            return View(jokes);
        }

        // POST: Jokes/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Jokes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Jokes'  is null.");
            }
            var jokes = await _context.Jokes.FindAsync(id);
            if (jokes != null)
            {
                _context.Jokes.Remove(jokes);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JokesExists(int id)
        {
          return (_context.Jokes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebJokesApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">JokesApp</h1>
    <h2>A Maior auturidade de humor num localhost!</h2>
    <img src="~/imagens/trollface.png" />
    
    
</div>

WebJokesApp/Views/Jokes/Create.cshtml
@model WebJokesApp.Models.Jokes

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                Pergunta@* <label asp-for="JokePergunta" class="control-label"></label> *@
                <input asp-for="JokePergunta" class="form-control" />
                <span asp-validation-for="JokePergunta" class="text-danger"></span>
            </div>
            <div class="form-group">
                Resposta:@* <label asp-for="JokeResposta" class="control-label"></label> *@
                <input asp-for="JokeResposta" class="form-control" />
                <span asp-validation-for="JokeResposta" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <p></p>
    <a asp-action="Index">Voltar Atrás</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebJokesApp/Views/Jokes/Delete.cshtml
@model WebJokesApp.Models.Jokes

@{
    ViewData["Title"] = "Delete";
}

<h1>Apagar</h1>

<h3>Tens a certeza que queres apagar?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokePergunta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokePergunta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokeResposta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokeResposta)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar Atrás</a>
    </form>
</div>

WebJokesApp/Views/Jokes/Details.cshtml
@model WebJokesApp.Models.Jokes

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-1">
            @* @Html.DisplayNameFor(model => model.JokePergunta) *@
            Então e
        </dt>
        <dd class = "col-sm-11">
            @Html.DisplayFor(model => model.JokePergunta)
        </dd>
        <dt class = "col-sm-1">
            @* @Html.DisplayNameFor(model => model.JokeResposta) *@
            Ora pois
        </dt>
        <dd class = "col-sm-11">
            @Html.DisplayFor(model => model.JokeResposta)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a asp-action="Index">Voltar Atrás</a>
</div>

WebJokesApp/Views/Jokes/Edit.cshtml
@model WebJokesApp.Models.Jokes

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="JokePergunta" class="control-label"></label>
                <input asp-for="JokePergunta" class="form-control" />
                <span asp-validation-for="JokePergunta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JokeResposta" class="control-label"></label>
                <input asp-for="JokeResposta" class="form-control" />
                <span asp-validation-for="JokeResposta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <p></p>
    <a asp-action="Index">Voltar Atrás</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebJokesApp/Views/Jokes/Index.cshtml
@model IEnumerable<WebJokesApp.Models.Jokes>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Criar Nova Anedota</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @* @Html.DisplayNameFor(model => model.JokePergunta) *@
                Pergunta-me por:
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.JokeResposta) *@
                Colocado por: 
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.JokePergunta)
            </td>
            <td>
                 @* @Html.DisplayFor(modelItem => item.JokeResposta)  *@
                    @* <partial name="_LoginPartial" /> *@
                    @Html.DisplayFor(modelItem => item.IdUser)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Apagar</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebJokesApp/Views/Jokes/ShowSearchForm.cshtml
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowformResults">  

            <div class="form-group">
                <label name="SearchPhrase" class="control-label">Pesquisar por:</label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class="form-group">
                <p></p>
                <input type="submit" value="Pesquisar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

WebJokesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebJokesApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebJokesApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/imagens/TrollFace2-transformed.png" width="100px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="Index">Jokes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="ShowSearchForm">Pesquisar</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebJokesApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>